### ISSUE TITLE
undefined function Hoa\Router\Http\mb_strtolower()

### ISSUE THREAD

**Issue by 1e1** [hoaproject/Router#39]
I run an Hoa application on a fresh Docker installation (official [PHP:FPM](https://github.com/docker-library/php/blob/7bd5c38db974ee629a815896add1ec568a1cc88c/7.0/fpm/Dockerfile)) with PHP7.0.3
```bash
root@vehicle-cli:/home/scm/Data/Bin# php -v
PHP 7.0.3 (cli) (built: Feb  5 2016 18:32:47) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```
I have to active PHP extension only if needed. 
I've just install mbstring. 

My router is: 
```php


$router
    ->get(
        'cars',
        '/v1/cars',
        '\Application\Controller\Car',
        'indexAction'
    )
    ->get(
        'car',
        '/v1/car/(?<car_id>\d+)',
        '\Application\Controller\Car',
        'getAction'
    );
```

It's good while I get `http://192.168.99.106:11080/v1/cars`
But while I get `http://192.168.99.106:11080/v1/car/123`, I read:
```
<b>Fatal error</b>:  Uncaught Error: Call to undefined function Hoa\Router\Http\mb_strtolower() in /home/scm/vendor/hoa/router/Http/Http.php:429
Stack trace:
#0 /home/scm/vendor/hoa/dispatcher/Dispatcher.php(133): Hoa\Router\Http\Http-&gt;route()
#1 /home/scm/Application/Public/index.php(37): Hoa\Dispatcher\Dispatcher-&gt;dispatch(Object(Hoa\Router\Http\Http))
```
As I read [mb_strtolower](http://php.net/mb_strtolower) is available on PHP7 with mbstring extension.
Do you see something wrong? 
```
root@vehicle-cli:/home/scm/Data/Bin# php -i | grep mb
Additional .ini files parsed => /usr/local/etc/php/conf.d/docker-php-ext-mbstring.ini
Zend Multibyte Support => provided by mbstring
xmlrpc_error_number => 0 => 0
mbstring
Multibyte string engine => libmbfl
libmbfl version => 1.3.2
mbstring extension makes use of "streamable kanji code filter and converter", which is distributed under the GNU Lesser General Public License version 2.1.
mbstring.detect_order => no value => no value
mbstring.encoding_translation => Off => Off
mbstring.func_overload => 0 => 0
mbstring.http_input => no value => no value
mbstring.http_output => no value => no value
mbstring.http_output_conv_mimetypes => ^(text/|application/xhtml\+xml) => ^(text/|application/xhtml\+xml)
mbstring.internal_encoding => no value => no value
mbstring.language => neutral => neutral
mbstring.strict_detection => Off => Off
mbstring.substitute_character => no value => no value
```

And I can test: 
```
root@vehicle-cli:/home/scm/Data/Bin# php -a
Interactive shell

php > $t = "GAbuZOmeuh";
php > echo mb_strtolower($t);
gabuzomeuh
```

**Comment by 1e1** [comment]
Perhaps, it is not the best fix. But I halt and re-run `docker-compose up` and it solved my issue. 
I had to restart fpm or nginx. 
I close the ticket and let it for the knowledge base ;)

**Comment by Hywan** [comment]
I didn't understand the issue to be frank :-/.

**Comment by 1e1** [comment]
I was surprised by `Hoa\Router\Http\mb_strtolower()` but it is not an Hoa issue. 
It is just I did't known how install a PHP extension on a Docker image. 
As Hoa is pointed by the error message, it could be interesting to keep an archive of this "issue" if an other newbie Google this error.
